version = 0.1

[default.deploy.parameters]
stack_name = "projetodebancodedadosfinal-v1"
resolve_s3 = true
s3_bucket = "projetodebancodedados-01"
s3_prefix = "projetodebancodedadosfinal-v1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "sa-east-1"
